spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/permission?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  aop:
    proxy-target-class:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
my:
  shiro:
      # 后端免认证接口 url
      anonUrl: /login,/actuator/*,/captcha.jpg
      # token有效期，单位秒
      jwtTimeOut: 3600

server:
  port: 8080
